-- migrate:up

CREATE TABLE users
(
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  given_name VARCHAR(191),
  family_name VARCHAR(191),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

-- migrate:down

DROP TABLE users;
